from __future__ import annotations
from datetime import date
from app.database import SessionLocal
from app.models.report_month import ReportMonth
from app.models.enums import ReportStatus

db = SessionLocal()

client_id = "22aa3418-4c06-4bf5-8c12-e7ea9135e850"
month_date = date(2026, 8, 1)

# Delete if exists
existing = db.query(ReportMonth).filter_by(client_id=client_id, month=month_date).first()
if existing:
    db.delete(existing)
    db.commit()

snapshot_data = {
    "gsc": {"clicks": 1250},
    "ga4": {"sessions": 4200},
    "rankings": {"summary": {"improved": 15, "declined": 4, "top_10": 8, "11_20": 12, "21_50": 25, "51_plus": 40}},
    "kpi_deltas": {"gsc": {"clicks": 150}, "ga4": {"sessions": 400}},
    "ai_visibility": [{"mentioned": True}, {"mentioned": True}, {"mentioned": False}],
    "sources": {"gsc": "manual", "ga4": "api", "rankings": "api", "ai_visibility": "manual"}
}

report = ReportMonth(
    client_id=client_id,
    month=month_date,
    status=ReportStatus.draft,
    snapshot=snapshot_data,
    narrative="This is a real-data executive summary generated by Groq. It highlights the strong growth in organic sessions and the positive trajectory of keyword rankings over the month of August.",
    published_by=None
)

db.add(report)
db.commit()

print("Report seeded.")
