"""refactor_links

Revision ID: 079510df09bc
Revises: 6fa3a84e4029
Create Date: 2026-09-02 12:17:00.909113
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079510df09bc'
down_revision: Union[str, None] = '6fa3a84e4029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('count', sa.Integer(), server_default='1', nullable=False))
    op.alter_column('links', 'domain',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('links', 'url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('uq_link_client_month_url', 'links', type_='unique')
    op.create_unique_constraint('uq_link_client_month_url_activity', 'links', ['client_id', 'month', 'url', 'activity_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_link_client_month_url_activity', 'links', type_='unique')
    op.create_unique_constraint('uq_link_client_month_url', 'links', ['client_id', 'month', 'url'])
    op.alter_column('links', 'url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('links', 'domain',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('links', 'count')
    # ### end Alembic commands ###
