"""cleanup_and_ledger_constraints

Revision ID: 12b4517f7974
Revises: 6d113129603e
Create Date: 2026-08-25 11:10:21.977408
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b4517f7974'
down_revision: Union[str, None] = '6d113129603e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add columns as nullable
    op.add_column('ai_mentions', sa.Column('month', sa.Date(), nullable=True))
    op.add_column('links', sa.Column('month', sa.Date(), nullable=True))

    # 2. Populate month columns
    op.execute("UPDATE ai_mentions SET month = date_trunc('month', captured_on)::date")
    op.execute("UPDATE links SET month = date_trunc('month', created_on)::date")

    # 3. Alter columns to be NOT NULL
    op.alter_column('ai_mentions', 'month', nullable=False)
    op.alter_column('links', 'month', nullable=False)

    # 4. Deduplicate tables
    # Activities
    op.execute("""
        DELETE FROM activities
        WHERE id NOT IN (
            SELECT DISTINCT ON (client_id, month, activity_type) id
            FROM activities
            ORDER BY client_id, month, activity_type, count DESC
        )
    """)
    # AI Mentions
    op.execute("""
        DELETE FROM ai_mentions
        WHERE id NOT IN (
            SELECT DISTINCT ON (client_id, month, prompt_id, platform) id
            FROM ai_mentions
            ORDER BY client_id, month, prompt_id, platform, captured_on DESC
        )
    """)
    # Links
    op.execute("""
        DELETE FROM links
        WHERE id NOT IN (
            SELECT DISTINCT ON (client_id, month, url) id
            FROM links
            ORDER BY client_id, month, url, created_on DESC
        )
    """)
    # Screenshots
    op.execute("""
        DELETE FROM screenshots
        WHERE id NOT IN (
            SELECT DISTINCT ON (client_id, month, keyword_id) id
            FROM screenshots
            ORDER BY client_id, month, keyword_id, id DESC
        )
    """)

    # 5. Apply Unique Constraints
    op.create_unique_constraint('uq_activity_client_month_type', 'activities', ['client_id', 'month', 'activity_type'])
    op.create_unique_constraint('uq_aimention_client_month_prompt_plat', 'ai_mentions', ['client_id', 'month', 'prompt_id', 'platform'])
    op.create_unique_constraint('uq_link_client_month_url', 'links', ['client_id', 'month', 'url'])
    op.create_unique_constraint('uq_screenshot_client_month_kw', 'screenshots', ['client_id', 'month', 'keyword_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_screenshot_client_month_kw', 'screenshots', type_='unique')
    op.drop_constraint('uq_link_client_month_url', 'links', type_='unique')
    op.drop_column('links', 'month')
    op.drop_constraint('uq_aimention_client_month_prompt_plat', 'ai_mentions', type_='unique')
    op.drop_column('ai_mentions', 'month')
    op.drop_constraint('uq_activity_client_month_type', 'activities', type_='unique')
    # ### end Alembic commands ###
