from __future__ import annotations
"""Add sync_run_id to provider_tasks

Revision ID: 22fe94361d56
Revises: 0016
Create Date: 2026-08-16 19:08:27.902075
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22fe94361d56'
down_revision: Union[str, None] = '0016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_tasks', sa.Column('sync_run_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'provider_tasks', 'sync_runs', ['sync_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provider_tasks', type_='foreignkey')
    op.drop_column('provider_tasks', 'sync_run_id')
    # ### end Alembic commands ###
