"""Add theme_color to Client

Revision ID: 4242b6f8c299
Revises: 92b7100c8ca5
Create Date: 2026-08-25 05:45:36.029754
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4242b6f8c299'
down_revision: Union[str, None] = '92b7100c8ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('theme_color', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'theme_color')
    # ### end Alembic commands ###
