"""rbac_hierarchy

Revision ID: 6d113129603e
Revises: a1b2c3d4e5f6
Create Date: 2026-08-25 07:29:43.017921
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d113129603e'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Manually added ENUM migration
    op.execute("ALTER TYPE user_role RENAME TO user_role_old")
    op.execute("CREATE TYPE user_role AS ENUM ('super_admin', 'manager', 'user')")
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE user_role USING 'user'::user_role")
    op.execute("DROP TYPE user_role_old")

    op.create_table('user_project_assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clients', sa.Column('manager_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'clients', 'users', ['manager_id'], ['id'])
    op.add_column('users', sa.Column('manager_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'manager_id')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'manager_id')
    op.drop_table('user_project_assignments')
    
    # Manually added ENUM downgrade
    op.execute("ALTER TYPE user_role RENAME TO user_role_new")
    op.execute("CREATE TYPE user_role AS ENUM ('agency_admin', 'agency_staff', 'client_manager')")
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE user_role USING 'agency_staff'::user_role")
    op.execute("DROP TYPE user_role_new")
    # ### end Alembic commands ###
