from __future__ import annotations
"""Add cost to sync_runs

Revision ID: 6f0c1f4fb843
Revises: 22fe94361d56
Create Date: 2026-08-16 19:44:30.498004
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f0c1f4fb843'
down_revision: Union[str, None] = '22fe94361d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_runs', sa.Column('cost', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_runs', 'cost')
    # ### end Alembic commands ###
