"""add_search_volume_to_keywords

Revision ID: 6fa3a84e4029
Revises: 91825f32745c
Create Date: 2026-09-02 10:43:31.600563
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa3a84e4029'
down_revision: Union[str, None] = '91825f32745c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keywords', sa.Column('search_volume', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keywords', 'search_volume')
    # ### end Alembic commands ###
