"""change business_type to text

Revision ID: 92b7100c8ca5
Revises: babdfc1b41e7
Create Date: 2026-08-21 06:12:08.777987
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92b7100c8ca5'
down_revision: Union[str, None] = 'babdfc1b41e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'business_type',
               existing_type=postgresql.ENUM('ecommerce', 'leadgen', 'local', 'saas', name='business_type'),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'business_type',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('ecommerce', 'leadgen', 'local', 'saas', name='business_type'),
               existing_nullable=False)
    # ### end Alembic commands ###
