from __future__ import annotations
"""create cost guardrail models

Revision ID: 93135179bc1c
Revises: 6f0c1f4fb843
Create Date: 2026-08-16 20:06:23.510975
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93135179bc1c'
down_revision: Union[str, None] = '6f0c1f4fb843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_provider_costs',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('cost', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'provider')
    )
    op.create_table('provider_states',
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('provider')
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_states')
    op.drop_table('daily_provider_costs')
    # ### end Alembic commands ###
