"""Add client_id to users

Revision ID: babdfc1b41e7
Revises: bad71c33d3dd
Create Date: 2026-08-21 05:54:07.623246
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'babdfc1b41e7'
down_revision: Union[str, None] = 'bad71c33d3dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('client_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'client_id')
    # ### end Alembic commands ###
